# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93ff220d7e0fb9ab525d422dec686b4cb5a602ebf6d910ff48208dfd8cffe9bfae188eaf6589b67b45cbae3a2de5fad7e7a16be3cd277cd80e7da9e494773166

test:
  secret_key_base: bd861e91e257fed4271396eb36c9fa037b79e39fb093f59555c18687af33d02f4a151a98a0ec784d18e87eb3bc620bee964777ed43e7f610c99bb8c4fccbd564

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
